name: hugo-blog

services:
  build:
    image: hugomods/hugo:exts-non-root
    command: build --minify --gc
    volumes:
      - "./:/src"

  serve:
    image: hugomods/hugo:exts-non-root
    command: >-
      server --poll 1000ms --buildDrafts --noHTTPCache --renderToMemory
             --baseURL http://127.0.0.1 --port 13130 
    volumes:
     - "./:/src"
     - "~/hugo_cache:/tmp/hugo_cache"
    ports:
     - "13130:13130"